# Generated by Django 5.0 on 2023-12-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
